### ISSUE TITLE
Corregir redacción

### ISSUE THREAD

**Issue by miltonlab** [CIS032/tarea-ch2hw1-juego-de-cartas-21-JhonCarrion#1]
Muy loable la descripción colocada en Readme.md, pero por favor corregir la ortografía.

**Comment by JhonCarrion** [comment]
Error mío... No me fijé antes de corregir.... fue por escribir rápido

**Comment by JhonCarrion** [comment]
He realizado la corrección de la ortografía.. sus observaciones son de mucha ayuda. Gracias!!!!

**Comment by miltonlab** [comment]
Ok
