### ISSUE TITLE
Traducir comentarios

### ISSUE THREAD

**Issue by miltonlab** [CIS032/tarea-ch2hw1-juego-de-cartas-21-JhonCarrion#2]
Sería saludable si también se tradujecen los comentarios en los archivos fuente.

**Comment by JhonCarrion** [comment]
Es verdad, si no se entiende el código al traducir los comentarios se tendrá una buena referencia de este.

**Comment by JhonCarrion** [comment]
he traducido todos los comentarios como aconsejo ...... gracias!!!

**Comment by miltonlab** [comment]
Listo
